In [25]:
import pandas as pd

In [12]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [ ]:
pd.Series(my_list)
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [20]:
pd.Series(arr)
pd.Series(arr,index=arr)

10    10
20    20
30    30
dtype: int64

In [21]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [24]:
import numpy as np
import pandas as pd

# Creating a DataFrame
data = {
    "Name": ['John', 'Anna', 'Peter', 'Linda'],
    "Age": [28, 34, 29, 42],
    "City": ['New York', 'Paris', 'Berlin', 'London'],
    "Salary": [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:

data_list = {
    "Name": ['John', 'Anna', 'Peter', 'Linda'],
    "Age": [28, 34, 29, 42],
    "City": ['New York', 'Paris', 'Berlin', 'London'],
    "Salary": [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data_list)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df[["Age","City"]]

   Age      City
0   28  New York
1   34     Paris
2   29    Berlin
3   42    London

In [50]:
df["Occupation"] = ["doctor","engineer","plumber","army officer"]
df

    Name  Age      City  Salary    Occupation
0   John   28  New York   65000        doctor
1   Anna   34     Paris   70000      engineer
2  Peter   29    Berlin   62000       plumber
3  Linda   42    London   85000  army officer

In [40]:
df.drop("Occupation", axis =1,inplace =True)

In [49]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [42]:
df.loc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [55]:
df.loc[3] [["City","Salary"]]

City      London
Salary     85000
Name: 3, dtype: object

In [56]:
df.loc[[2,3]] [["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [58]:
df[df["Age"] >30]

    Name  Age    City  Salary    Occupation
1   Anna   34   Paris   70000      engineer
3  Linda   42  London   85000  army officer

In [61]:
df[df["Age"] >20]

    Name  Age      City  Salary    Occupation
0   John   28  New York   65000        doctor
1   Anna   34     Paris   70000      engineer
2  Peter   29    Berlin   62000       plumber
3  Linda   42    London   85000  army officer

In [62]:
df[df["Age"] >20]

    Name  Age      City  Salary    Occupation
0   John   28  New York   65000        doctor
1   Anna   34     Paris   70000      engineer
2  Peter   29    Berlin   62000       plumber
3  Linda   42    London   85000  army officer

In [63]:
df[(df["Age"] >30) & (df["City"] == "Paris")]

   Name  Age   City  Salary Occupation
1  Anna   34  Paris   70000   engineer

In [71]:
import numpy as np
import pandas as pd

# The data value with missing (NaN) values
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [68]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [70]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [72]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [75]:
df.dropna(thresh=2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [76]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [77]:
values={"A":10,"B":100,"C":50,"D":20}
df.fillna(value=values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  20.0
2  10.0  3   3.0  20.0
3   4.0  4  50.0  20.0
4   5.0  5  50.0   5.0

In [4]:
import numpy as np
import pandas as pd

# DataFrame 1: Employees
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary Information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [7]:
pd.merge(employees,salaries,on="employee_id",how ="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [8]:
pd.merge(employees,salaries,on="employee_id",how ="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [9]:
pd.merge(employees,salaries,on="employee_id",how ="left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [10]:
pd.merge(employees,salaries,on="employee_id",how="right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [11]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

# DataFrame 2
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [12]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [13]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [24]:
import numpy as np
import pandas as pd

# Create data
data = {
    "Category": ["A", "B", "A", "B", "A", "B", "A", "B"],
    "Store": ["S1", "S1", "S2", "S2", "S1", "S2", "S2", "S1"],
    "Sales": [100, 200, 150, 250, 120, 180, 200, 300],
    "Quantity": [10, 15, 12, 18, 8, 20, 15, 25],
    "Date": pd.date_range("2023-01-01", periods=8)
}

df=pd.DataFrame(data)

In [23]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08