In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv(r"sales_data.csv")
df

  Product  Price  Quantity    City
0  Laptop  50000         2  Mumbai
1   Phone  20000         5   Delhi
2  Tablet  15000         3    Pune
3  Laptop  50000         1  Mumbai
4   Phone  20000         2   Delhi
5  Tablet  15000         4    Pune

In [13]:
df.columns=df.columns.str.strip()
df.head()

  Product  Price  Quantity    City
0  Laptop  50000         2  Mumbai
1   Phone  20000         5   Delhi
2  Tablet  15000         3    Pune
3  Laptop  50000         1  Mumbai
4   Phone  20000         2   Delhi

TOTAL SALES

In [25]:
df["total_sales"] =df["Price"] * df["Quantity"]
print(total_sales)

0    100000
1    100000
2     45000
3     50000
4     40000
5     60000
dtype: int64

AVERAGE_SALES OF CITY

In [26]:
city_avg_sales =df.groupby("City")["total_sales"].mean()
print(city_avg_sales)

City
Delhi     70000.0
Mumbai    75000.0
Pune      52500.0
Name: total_sales, dtype: float64

MOST BUYED PRODUCT

In [28]:
top_products =df.groupby("Product") ["total_sales"].sum().idxmax()
print(top_products)

Laptop

SAVE THAT DATA

In [29]:
df.to_csv("output.csv",index=False)