In [71]:
import numpy as np
import pandas as pd

In [72]:
df=pd.read_csv(r"student_data.csv")
df

    Name  Maths  Science  English
0  Rahul     80       75       85
1  Priya     90       88       92
2   Amit     70       72       68
3  Sneha     85       80       78
4  Rahul     80       75       85
5   Amit     70       72       68

AVERAGE MARKS IN  MATH AND SCIENCE

In [73]:
df["average"] =(df["Maths"]+ df["Science"]+ df["English"]) /3
df.head()

    Name  Maths  Science  English  average
0  Rahul     80       75       85     80.0
1  Priya     90       88       92     90.0
2   Amit     70       72       68     70.0
3  Sneha     85       80       78     81.0
4  Rahul     80       75       85     80.0

TOP STUDENTS

In [76]:
top_student=df.loc[df['average'].idxmax()]
print(top_student)

Name       Priya
Maths         90
Science       88
English       92
average     90.0
Name: 1, dtype: object

In [77]:
duplicate_name=df.drop_duplicates(subset="Name")
print(duplicate_name)

    Name  Maths  Science  English  average
0  Rahul     80       75       85     80.0
1  Priya     90       88       92     90.0
2   Amit     70       72       68     70.0
3  Sneha     85       80       78     81.0

ADDING GRADE

In [79]:
def grade(avg):
    if avg >=90:
        return "A"
    elif avg >=80:
        return "B"
    elif avg >=70:
        return "C"
    else:
        return "D"
Grade=df["average"].apply(grade)
print(Grade)

0    B
1    A
2    C
3    B
Name: average, dtype: str